import { parseBaseToken, ParsedClassToken } from "../utils";

// 모든 유틸리티 prefix를 중복 없이 하나의 배열에 선언 (카테고리별 주석 구분)
export const ALL_UTILITY_PREFIXES = [
  // alignment
  "place-content",
  "place-items",
  "place-self",
  "justify-items",
  "justify-self",
  "align-items",
  "align-self",
  "justify",
  "align",

  // box
  "box-decoration-clone",
  "box-decoration-slice",
  "box-decoration-break",
  "box-decoration",
  "border-collapse",
  "border-separate",
  "drop-shadow",

  // break
  "break-inside",
  "break-before",
  "break-after",

  // color
  "decoration",
  "outline",
  "shadow",
  "stroke",
  "accent",
  "caret",
  "fill",
  "text",

  // colorScheme
  "scheme-normal",
  "scheme-dark",
  "scheme-light",
  "scheme-light-dark",
  "scheme-only-dark",
  "scheme-only-light",
  "scheme",
  "forced-color-adjust-auto",
  "forced-color-adjust-none",
  "forced-color-adjust",

  // effects
  "mix-blend",
  "opacity",
  "blur",
  "brightness",
  "contrast",
  "grayscale",
  "hue-rotate",
  "invert",
  "saturate",
  "sepia",
  "backdrop-blur",
  "backdrop-brightness",
  "backdrop-contrast",
  "backdrop-grayscale",
  "backdrop-hue-rotate",
  "backdrop-invert",
  "backdrop-opacity",
  "backdrop-saturate",
  "backdrop-sepia",
  "backdrop",
  "will-change",

  // flexGrid/layout
  "inline-flex",
  "inline-grid",
  "flex-basis",
  "flex-direction",
  "flex-wrap",
  "flex-grow",
  "flex-shrink",
  "flex-auto",
  "flex-initial",
  "flex-none",
  "flex",
  "order",
  "grid-cols",
  "grid-rows",
  "grid-flow",
  "col-span",
  "col-start",
  "col-end",
  "row-span",
  "row-start",
  "row-end",
  "auto-cols",
  "auto-rows",
  "grid",
  "gap-x",
  "gap-y",
  "gap",

  // font
  "normal-nums",
  "ordinal",
  "slashed-zero",
  "lining-nums",
  "oldstyle-nums",
  "proportional-nums",
  "tabular-nums",
  "diagonal-fractions",
  "stacked-fractions",
  "italic",
  "not-italic",
  "font-stretch",
  "antialiased",
  "subpixel-antialiased",

  // gradient
  "bg-gradient-to",
  "bg-linear",
  "bg-radial",
  "bg-conic",
  "from",
  "via",
  "to",
  "gradient",

  // grid
  "grid-auto-cols-auto",
  "grid-auto-cols-min",
  "grid-auto-cols-max",
  "grid-auto-cols-fr",
  "grid-auto-cols",
  "columns",
  "col-end-auto",
  "col-end",

  // list
  "list-disc",
  "list-decimal",
  "list-none",
  "list-style-type",
  "hyphens-none",
  "hyphens-manual",
  "hyphens-auto",
  "hyphens",

  // mask
  "mask-type",
  "mask-size",
  "mask-repeat",
  "mask-position",
  "mask-mode",

  // misc
  "white-space",
  "display",
  "float",
  "clear",
  "content",
  "filter",

  // object
  "object-position",
  "object-fit",
  "object",

  // outline
  "outline-width",
  "outline-style",
  "outline-offset",

  // overflow
  "overscroll-x",
  "overscroll-y",
  "overscroll",
  "overflow-x",
  "overflow-y",
  "overflow",
  "scroll-auto",
  "scroll-smooth",
  "scroll-mx",
  "scroll-my",
  "scroll-mt",
  "scroll-mb",
  "scroll-ml",
  "scroll-mr",
  "scroll-px",
  "scroll-py",
  "scroll-pt",
  "scroll-pb",
  "scroll-pl",
  "scroll-pr",
  "scroll-p",
  "scroll-m",

  // position
  "inset-x",
  "inset-y",
  "inset",
  "top",
  "right",
  "bottom",
  "left",
  "z",

  // scroll
  "scroll-padding-inline",
  "scroll-padding-block",
  "scroll-padding-top",
  "scroll-padding-right",
  "scroll-padding-bottom",
  "scroll-padding-left",
  "scroll-padding-inline-start",
  "scroll-padding-inline-end",
  "scroll-padding",
  "scroll-margin-inline",
  "scroll-margin-block",
  "scroll-margin-top",
  "scroll-margin-right",
  "scroll-margin-bottom",
  "scroll-margin-left",
  "scroll-margin-inline-start",
  "scroll-margin-inline-end",
  "scroll-margin",
  "snap-start",
  "snap-end",
  "snap-center",
  "snap-align-none",
  "snap-normal",
  "snap-always",
  "snap-none",
  "snap-x",
  "snap-y",
  "snap-both",
  "snap-mandatory",
  "snap-proximity",

  // sizing
  "min-w",
  "max-w",
  "min-h",
  "max-h",
  "aspect",
  "size",
  "w",
  "h",
  "field-sizing-fixed",
  "field-sizing-content",
  "field-sizing",

  // spacing
  "space-x",
  "space-y",
  "mx",
  "my",
  "mt",
  "mb",
  "ml",
  "mr",
  "px",
  "py",
  "pt",
  "pb",
  "pl",
  "pr",
  "m",
  "p",

  // svg
  "stroke-width",
  "stroke",
  "fill",

  // table
  "table-caption",
  "table-header-group",
  "table-footer-group",
  "table-row-group",
  "table-column-group",
  "table-row",
  "table-cell",
  "table-column",
  "table-fixed",
  "table-auto",
  "border-spacing",
  "caption-top",
  "caption-bottom",
  "table",

  // text
  "indent",
  "overflow-wrap-break-word",
  "overflow-wrap-anywhere",
  "overflow-wrap-normal",
  "overflow-wrap",
  "break-normal",
  "break-all",
  "break-keep",
  "word-break",
  "text-shadow",

  // transform
  "transform-origin",
  "transform-style",
  "transform",
  "translate-x",
  "translate-y",
  "translate-z",
  "translate",
  "skew-x",
  "skew-y",
  "skew",
  "perspective-origin",
  "perspective",
  "rotate-x",
  "rotate-y",
  "rotate-z",
  "rotate",
  "backface-hidden",
  "backface-visible",
  "backface-visibility",

  // transition/animation
  "transition-property",
  "transition-behavior",
  "transition-timing-function",
  "transition-duration",
  "transition-delay",
  "transition",
  "duration",
  "delay",
  "ease",
  "animation",
  "animate",

  // typography
  "line-clamp",
  "overline",
  "no-underline",
  "normal-case",
  "text-ellipsis",
  "text-clip",
  "uppercase",
  "lowercase",
  "capitalize",
  "truncate",
  "underline",
  "leading",
  "tracking",
  "font",

  // visibility
  "isolation",
  "visible",
  "invisible",
  "collapse",

  // border
  "border-tl",
  "border-tr",
  "border-bl",
  "border-br",
  "border-t",
  "border-b",
  "border-l",
  "border-r",
  "border-x",
  "border-y",
  "border",
  "divide-x",
  "divide-y",
  "divide-t",
  "divide-b",
  "divide-l",
  "divide-r",
  "divide",
  "ring",
  "rounded-tl",
  "rounded-tr",
  "rounded-bl",
  "rounded-br",
  "rounded-t",
  "rounded-b",
  "rounded-l",
  "rounded-r",
  "rounded-x",
  "rounded-y",
  "rounded-ss",
  "rounded-se",
  "rounded-es",
  "rounded-ee",
  "rounded-s",
  "rounded-e",
  "rounded",

  // background
  "bg-none",
  "bg-blend",
  "bg-clip",
  "bg-origin",
  "bg-repeat",
  "bg-no-repeat",
  "bg-size",
  "bg-position",
  "bg-fixed",
  "bg-local",
  "bg-scroll",
  "bg",

  // interactivity
  "pointer-events",
  "user-select",
  "touch-action",
  "resize",
];

export function parseUtilityBase(token: string): ParsedClassToken | { type: 'unknown'; raw: string } {
  const result = parseBaseToken(token, ALL_UTILITY_PREFIXES, true, true);
  if (result) return result;
  return { type: "unknown", raw: token };
}
