import { AstNode } from "./ast";
import { Context } from "./context";
import { getModifier, getUtility } from "./registry";
import { ParsedUtility, ParsedModifier } from "./parser";
import { astToCss, rootToCss } from "./astToCss";
import { optimizeAst } from "./engine";

/**
 * The structured input format for BaroCSS engine.
 * Designed to be easily generated by AI models.
 */
export type BaroJsonInput = {
    /**
     * The core utility to apply.
     * Corresponds to the utility class name in Tailwind (e.g., 'bg-red-500', 'p-4').
     */
    utility: {
        /**
         * The utility prefix.
         * @example 'bg', 'text', 'p', 'm', 'flex', 'hidden'
         */
        name: string;

        /**
         * The value of the utility.
         * Optional for boolean utilities like 'flex', 'hidden'.
         * @example 'red-500', '4', 'lg', '#123456'
         */
        value?: string;

        /**
         * Whether the value is an arbitrary value (JIT).
         * @default false
         * @example true for 'bg-[#123456]'
         */
        arbitrary?: boolean;

        /**
         * Whether the value is negative.
         * @default false
         * @example true for '-m-4'
         */
        negative?: boolean;

        /**
         * Opacity modifier for colors.
         * @example '50' for 'bg-red-500/50'
         */
        opacity?: string;

        /**
         * Whether the value is a custom property.
         * @default false
         * @example true for 'bg-(--my-bg)'
         */
        customProperty?: boolean;

        /**
         * Whether the utility is marked as important (!).
         * @default false
         * @example true for '!bg-red-500'
         */
        important?: boolean;
    };

    /**
     * List of variants/modifiers to apply.
     * Applied from outside to inside (left to right in string format).
     * @example ['hover', 'focus'] for 'hover:focus:bg-red-500'
     */
    variants?: Array<string | BaroVariant>;
};

/**
 * Detailed configuration for a variant.
 */
export type BaroVariant = {
    /**
     * The name of the variant.
     * @example 'hover', 'focus', 'sm', 'data', 'group-hover'
     */
    name: string;

    /**
     * The value for parameterized variants.
     * @example 'open' for 'data-[state=open]'
     */
    value?: string;

    /**
     * Whether the variant is arbitrary.
     * @default false
     * @example true for 'min-[320px]'
     */
    arbitrary?: boolean;
};

/**
 * Converts a single BaroJsonInput object into an AST tree.
 * Bypasses string parsing and directly invokes utility/modifier handlers.
 *
 * @param input BaroJsonInput object
 * @param ctx Context
 * @returns AstNode[]
 */
export function jsonToAst(input: BaroJsonInput, ctx: Context): AstNode[] {
    // 1. Find Utility Handler
    // Try to find exact match first (e.g. 'text-center' from { name: 'text', value: 'center' })
    let utilReg = getUtility().find((u) => u.name === input.utility.name);

    if (input.utility.value && !input.utility.arbitrary && !input.utility.customProperty) {
        const fullName = `${input.utility.name}-${input.utility.value}`;
        const exactMatch = getUtility().find((u) => u.name === fullName);
        if (exactMatch) {
            utilReg = exactMatch;
            // If exact match found, the value is consumed by the name, so we pass empty string or the value itself depending on handler
            // Static utilities usually ignore the value argument if they are exact matches.
        }
    }

    if (!utilReg) {
        // eslint-disable-next-line no-console
        console.warn(`[jsonToAst] Unknown utility: "${input.utility.name}"`);
        return [];
    }

    // 2. Construct ParsedUtility object (mocking the parser output)
    const parsedUtility: ParsedUtility = {
        prefix: input.utility.name,
        value: input.utility.value,
        arbitrary: input.utility.arbitrary,
        negative: input.utility.negative,
        opacity: input.utility.opacity,
        important: input.utility.important,
        customProperty: input.utility.customProperty,
        category: utilReg.category,
        priority: utilReg.priority,
    };

    // 3. Generate Initial AST
    // Handle negative value logic if needed (similar to parser)
    let value = input.utility.value;
    if (input.utility.negative && value) {
        value = "-" + value;
    }

    // If we found an exact match (e.g. text-center), the handler might expect the value to be part of the name or handled differently.
    // Static utilities (like text-center) usually don't use the value argument.
    // Functional utilities (like text) use the value argument.
    // We pass the value as is.
    let ast = utilReg.handler(value || "", ctx, parsedUtility, utilReg) || [];

    // 4. Apply Variants (Modifiers)
    // Variants are applied from right to left (inner to outer) in the string representation
    // e.g., sm:hover:bg-red-500 -> hover wraps bg, then sm wraps hover
    // In JSON, variants are usually listed [sm, hover].
    // To wrap correctly (sm(hover(bg))), we process from right to left (hover then sm).

    type Wrapper = {
        type: string;
        items?: AstNode[];
        selector?: string;
        flatten?: boolean;
        source?: string;
        name?: string;
        params?: string;
    };

    if (input.variants && input.variants.length > 0) {
        const wrappers: Wrapper[] = [];
        const selector = "&"; // Base selector

        // Process variants from right to left
        for (let i = input.variants.length - 1; i >= 0; i--) {
            const variantInput = input.variants[i];
            const variantName =
                typeof variantInput === "string" ? variantInput : variantInput.name;
            const variantValue =
                typeof variantInput === "string" ? undefined : variantInput.value;
            const variantArbitrary =
                typeof variantInput === "string" ? false : variantInput.arbitrary;

            // Construct ParsedModifier object
            const parsedModifier: ParsedModifier = {
                type: variantName,
                value: variantValue,
                arbitrary: variantArbitrary,
            };

            let matchKey = variantName;

            // Arbitrary variant handling (e.g. min-[320px] or [dir="rtl"])
            if (variantArbitrary && variantValue) {
                if (variantName) {
                    // Named arbitrary variant: min-[320px]
                    matchKey = `${variantName}-[${variantValue}]`;
                    parsedModifier.type = matchKey;
                } else {
                    // Pure arbitrary variant: [dir="rtl"]
                    matchKey = `[${variantValue}]`;
                    parsedModifier.type = matchKey;
                }
            } else if (variantValue) {
                // Parameterized variant (e.g. data-[state=open])
                // The registry match function usually expects the full string like 'data-[state=open]'
                matchKey = `${variantName}-[${variantValue}]`;
                parsedModifier.type = matchKey;
            }

            const plugin = getModifier().find((p) => p.match(matchKey, ctx));

            if (!plugin) {
                // eslint-disable-next-line no-console
                console.warn(`[jsonToAst] Unknown variant: "${matchKey}"`);
                continue;
            }

            // Apply Modifier Logic (Wrap or Modify Selector)
            // This logic mirrors parseClassToAst in engine.ts
            if (plugin.wrap) {
                const items = plugin.wrap(parsedModifier, ctx);
                wrappers.push({
                    type: "wrap",
                    items: items,
                });
                continue;
            }

            if (plugin.modifySelector) {
                const result = plugin.modifySelector({
                    selector,
                    fullClassName: "JSON_GENERATED", // Placeholder
                    mod: parsedModifier,
                    context: ctx,
                    variantChain: [], // We might need to pass the full chain if needed
                    index: i,
                });

                if (typeof result === "string" && result.includes("&")) {
                    wrappers.push({ type: "rule", selector: result });
                } else if (typeof result === "object" && !Array.isArray(result) && (result as { selector?: string }).selector) {
                    const r = result as { selector: string; wrappingType?: string; flatten?: boolean; source?: string };
                    const wrappingType = r.wrappingType || "rule";
                    wrappers.push({
                        type: wrappingType,
                        selector: r.selector,
                        flatten: r.flatten,
                        source: r.source,
                    });
                } else if (Array.isArray(result)) {
                    // result is array of objects
                    wrappers.push({
                        type: "wrap",
                        items: (result as any[]).map((r) => ({
                            type: r.wrappingType || "rule",
                            selector: r.selector,
                            source: r.source,
                            nodes: [], // Placeholder, will be filled when wrapping
                        } as unknown as AstNode)),
                    });
                }
            }
        }

        // Nest wrappers (Wrappers are collected in reverse order of application, so we iterate to apply)
        for (let i = 0; i < wrappers.length; i++) {
            const wrap = wrappers[i];
            // Application logic same as engine.ts
            if (wrap.type === "wrap") {
                ast = (wrap.items as AstNode[]).map((item) => ({
                    ...item,
                    nodes: Array.isArray(ast) ? ast : [ast],
                }));
            } else if (wrap.type === "style-rule") {
                ast = [
                    {
                        type: "style-rule",
                        selector: wrap.selector!,
                        source: wrap.source,
                        nodes: Array.isArray(ast) ? ast : [ast],
                    },
                ];
            } else if (wrap.type === "at-rule") {
                ast = [
                    {
                        type: "at-rule",
                        name: wrap.name || "media",
                        params: wrap.params!,
                        source: wrap.source,
                        nodes: Array.isArray(ast) ? ast : [ast],
                    },
                ];
            } else if (wrap.type === "rule") {
                ast = [
                    {
                        type: "rule",
                        selector: wrap.selector!,
                        source: wrap.source,
                        nodes: Array.isArray(ast) ? ast : [ast],
                    },
                ];
            }
        }
    }

    return ast;
}

/**
 * Generates CSS from a list of BaroJsonInput objects.
 *
 * @param inputs Array of BaroJsonInput
 * @param ctx Context
 * @param opts Options (minify, etc.)
 * @returns CSS string
 */
export function generateCssFromJson(
    inputs: BaroJsonInput[],
    ctx: Context,
    opts?: { minify?: boolean }
): string {
    const allAtRootNodes: AstNode[] = [];
    const cssList: string[] = [];

    inputs.forEach((input) => {
        // 1. Convert JSON to AST
        const ast = jsonToAst(input, ctx);

        // 2. Optimize AST (dedup, merge, sort)
        const cleanAst = optimizeAst(ast);

        // 3. Extract at-root nodes
        cleanAst.forEach((node) => {
            if (node.type === "at-root") {
                allAtRootNodes.push(...node.nodes);
            }
        });

        // 4. Generate CSS for this block
        // We need a class name for the selector if it's not self-contained.
        // However, jsonToAst typically generates generic structures.
        // astToCss needs a baseSelector if the AST doesn't have one (e.g. style-rule).
        // But wait, standard utilities usually generate a rule with '&' or similar.
        // optimizeAst merges them.
        // If we don't provide a baseSelector to astToCss, it might fail if the rule is just '&'.
        // We need to decide:
        // A. Generate a hash class name?
        // B. Expect the user to provide a class name in JSON?
        // C. Use a generic class name?
        //
        // For now, let's assume the user wants the pure CSS properties or the AST is self-contained.
        // BUT, standard Tailwind utilities rely on the class name selector (e.g. .bg-red-500).
        // If we generate CSS, we need a selector.
        //
        // Let's auto-generate a class name based on the input if possible, or use a placeholder.
        // For this implementation, let's reconstruct a class-like name for the selector.

        let reconstructedName = input.utility.name;
        if (input.utility.value) reconstructedName += `-${input.utility.value}`;
        if (input.utility.arbitrary) reconstructedName = `${input.utility.name}-[${input.utility.value}]`;
        if (input.variants) {
            const variantsStr = input.variants.map(v => typeof v === 'string' ? v : v.name).join(':');
            reconstructedName = `${variantsStr}:${reconstructedName}`;
        }
        // Escape it
        // We can use a simple placeholder if we don't care about the class name matching exactly.
        // But for "generateCss", usually we want the class definition.

        const hasStyleRule = cleanAst.some((node) => node.type === "style-rule");
        const css = astToCss(cleanAst, hasStyleRule ? undefined : `.${reconstructedName.replace(/[^a-zA-Z0-9-_]/g, '\\$&')}`, {
            minify: opts?.minify,
            important: input.utility.important ?? false,
        });

        if (css) cssList.push(css);
    });

    const rootCss = rootToCss(allAtRootNodes);
    const finalCss = `${rootCss ? `:root,:host {${rootCss}}` : ""}${cssList.join(opts?.minify ? "" : "\n")}`;

    return finalCss;
}
